-- Order2Me: customer feedback for delivered orders
-- Run once in Supabase SQL Editor after multi_shop_migration.sql.

CREATE TABLE IF NOT EXISTS public.order_feedback (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id    bigint NOT NULL UNIQUE REFERENCES public.orders(id) ON DELETE CASCADE,
  customer_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  shop_id     bigint NOT NULL REFERENCES public.shops(id) ON DELETE CASCADE,
  rating      smallint NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment     text CHECK (comment IS NULL OR char_length(comment) <= 500),
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_order_feedback_shop_created
  ON public.order_feedback(shop_id, created_at DESC);

ALTER TABLE public.order_feedback ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Customers create feedback for delivered orders" ON public.order_feedback;
CREATE POLICY "Customers create feedback for delivered orders"
ON public.order_feedback FOR INSERT TO authenticated
WITH CHECK (
  customer_id = public.current_profile_id()
  AND EXISTS (
    SELECT 1
    FROM public.orders o
    WHERE o.id = order_id
      AND o.customer_id = public.current_profile_id()
      AND o.shop_id = shop_id
      AND o.status = 'delivered'
  )
);

DROP POLICY IF EXISTS "Customers read own feedback" ON public.order_feedback;
CREATE POLICY "Customers read own feedback"
ON public.order_feedback FOR SELECT TO authenticated
USING (customer_id = public.current_profile_id());

DROP POLICY IF EXISTS "Approved owners read shop feedback" ON public.order_feedback;
CREATE POLICY "Approved owners read shop feedback"
ON public.order_feedback FOR SELECT TO authenticated
USING (public.owns_approved_shop(shop_id));

DROP POLICY IF EXISTS "Admins read all feedback" ON public.order_feedback;
CREATE POLICY "Admins read all feedback"
ON public.order_feedback FOR SELECT TO authenticated
USING (public.is_admin());

-- Keep identity fields and the original rating immutable; customers may only
-- correct their optional comment. Delete is intentionally not exposed.
DROP POLICY IF EXISTS "Customers update own feedback comment" ON public.order_feedback;
CREATE POLICY "Customers update own feedback comment"
ON public.order_feedback FOR UPDATE TO authenticated
USING (customer_id = public.current_profile_id())
WITH CHECK (customer_id = public.current_profile_id());

CREATE OR REPLACE FUNCTION public.protect_order_feedback_identity()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.order_id := OLD.order_id;
  NEW.customer_id := OLD.customer_id;
  NEW.shop_id := OLD.shop_id;
  NEW.rating := OLD.rating;
  NEW.created_at := OLD.created_at;
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_protect_order_feedback_identity ON public.order_feedback;
CREATE TRIGGER trg_protect_order_feedback_identity
BEFORE UPDATE ON public.order_feedback
FOR EACH ROW EXECUTE FUNCTION public.protect_order_feedback_identity();

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'order_feedback'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.order_feedback;
  END IF;
END $$;
